### ISSUE TITLE
Error loading Plaid null appears to be back in v2.2.3

### ISSUE THREAD

**Issue by armsteadj1** [plaid/react-plaid-link#121]
I'm receiving the same `Error loading Plaid null` that appears to be reported in issue #86 when upgrading to v2.2.3. 

It does appear `react-script-hook` was upgraded to v1.1.0 in v2.2.3, I haven't dug in to see if that could be causing the issue or not. 

If I navigate away and back, everything works and there is no error.

I downgraded to v2.2.1 and it works fine.

**Comment by oaosman84** [comment]
I'm seeing this too but it's not consistently reproducible, it just seems to happen occasionally to some users.

**Comment by zsidnam** [comment]
I am experiencing this as well. It is (somewhat) consistent to reproduce if you have multiple components using the usePlaidLink hook loading at the same time. I have a use case where I want to have one PlaidLink control on the page for the user to link new institutions, and another PlaidLink control on the same page that will open Plaid in update mode for an existing institution link. In this scenario, I can keep refreshing the page, and about 50% - 75% of the time I will encounter this error which prevents one or the two controls from working.

**Comment by wnamen** [comment]
> I am experiencing this as well. It is (somewhat) consistent to reproduce if you have multiple components using the usePlaidLink hook loading at the same time. I have a use case where I want to have one PlaidLink control on the page for the user to link new institutions, and another PlaidLink control on the same page that will open Plaid in update mode for an existing institution link. In this scenario, I can keep refreshing the page, and about 50% - 75% of the time I will encounter this error which prevents one of the two controls from working.

Experiencing the same issue, @zsidnam were you ever able to figure out a solution?

**Comment by zsidnam** [comment]
@wnamen Unfortunately, I was not able to find a good solution for this. However, I added `<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js">` into my index.html as one user suggested in the comments at the bottom of #86 and this "fixed" the issue for us by making sure the script was loaded before the hooks get run. Not a permanent solution but it got us up and running until this issue gets resolved.

**Comment by alexandrasmith00** [comment]
Also experiencing this for production users using `v3.0.0`. I had previously had issues with the link declaring more than once, but that was solved in #109, not sure if that fix unintentionally caused this as well

**Comment by prashantabellad** [comment]
What is the latest on this??

**Comment by zallarak** [comment]
Experiencing this issue as well, pretty regularly

**Comment by jtdaugh** [comment]
We're seeing this issue too. Any update?

**Comment by mpvosseller** [comment]
I'm seeing this in 3.1.0.  For me the issue is highly reproducible when I use multiple "link" buttons on the page. On initial load / page refresh one button usually loads correctly while the other buttons often (but not always) fail. When one fails it remains disabled and there is a stack trace like the below. Sometimes (but not always) they all load correctly.

```
Error loading Plaid null
console.<computed> @ index.js:1
(anonymous) @ index.umd.js:355
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:590
flushWork @ scheduler.development.js:545
performWorkUntilDeadline @ scheduler.development.js:157
```

**Comment by ramkumarvs** [comment]
do we have a work around?

**Comment by prashantabellad** [comment]
> 
I added <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"> into my index.html

**Comment by ipam73** [comment]
This is happening to me as well. I have a use case where I need multiple link buttons on one page, and get this error every time on page load. I'm on version 3.1.0 using usePlaidLink hook.

`Error loading Plaid null `

For now, also using the workaround by adding <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"> into my index.html

**Comment by proverbface** [comment]
I can confirm as well this is still happening. @ipam73 solution works for now as a workaround. It would be great when this is fixed within the lib.

**Comment by skylarmb** [comment]
Interesting I thought we fixed this in 3.1.0 via #164. I'll have to take another look at the case where there are multiple link instances being initialized at the same time.

**Comment by yotavm** [comment]
we using 3.1.0 and still getting 
```Error loading Plaid null``` in some case
the one case that this will always happen is if the first page the user see is using plaid hook

**Comment by proverbface** [comment]
This is still an issue on v.3.2.0.  Any plans to fix it?

**Comment by SnapeEye** [comment]
Guys, is any minor release planned? npm says that last updated was 5 months ago, so the fix above is not delivered yet.
This issue is too unexpected as it blocks the whole integration with Plaid.

**Comment by skylarmb** [comment]
@SnapeEye I just published 3.2.2 which includes this fix, sorry for the delay!
