### ISSUE TITLE
Loading Plaid fails on initial page load

### ISSUE THREAD

**Issue by jgonera** [plaid/react-plaid-link#86]
I get `Error loading Plaid null` when using `usePlaidLink` every time I initially load my app in the browser. When I navigate away from the place where I use Plaid and navigate back, everything works.

The reason seems to be this check:
https://github.com/plaid/react-plaid-link/blob/62b457dd0ebce99de930c8a5dca838489c5e683a/src/usePlaidLink.ts#L36

From what I can tell, `loading` becomes `false`, but `window.Plaid` is not yet available (perhaps `react-script-hook` sets `loading` to false as soon as the script is downloaded but not when it's parsed/executed?). Checking `window.Plaid` in browser's console indicates that the library is loaded properly soon after the error.

**Comment by pbernasconi** [comment]
@jgonera could you share some sample code for how you're integrating with the hook?

**Comment by KyruCabading** [comment]
@pbernasconi Also interested in this issue. I get the same error when I'm running the hook. I'll try to make a sample repo and link it here. Mine might be due to SSR (nextJS) though with the hook.

**Comment by JPWallhorn** [comment]
Hey,

I'm using Plaid as a component and render it within another component and get the following error message when loading the page initially. Note: When I load a different page first, it works just fine:

`Error Loading Plaid: null`

Here's my page/component that wraps the PlaidLink (<Plaid /> contains the <PlaidLink/>
```
              <div className={styles.bankingOptionContainer}>
                <BankingOption className={styles.image} />
                <Plaid button onSuccess={onSuccess} />
              </div>
```

**Comment by rubendinho** [comment]
Experiencing the same issue after upgrading to v2.0 and using a standard configuration per the docs. 

After navigating away and back, the button works.

**Comment by joernroeder** [comment]
i am also getting `Error loading Plaid` with the hooks example

**Comment by skylarmb** [comment]
hello all, I am trying to reproduce this and have had no luck. Would anyone mind providing a minimal reproducible example, or at least letting me know what you are doing differently from this example repo: https://github.com/skylarmb/playground-react-plaid-link

**Comment by skylarmb** [comment]
Here is a nextjs app where I also failed to reproduce it https://github.com/skylarmb/playground-react-plaid-link-next

**Comment by atomkirk** [comment]
this happens randomly for me. It's like a race condition or something. I'm using the `<PlaidLink …` version

**Comment by atomkirk** [comment]
theres definitely a race condition. I copied your lib into my repo and modified it like this:

```
export const usePlaidLink = (options) => {
  // Asynchronously load the plaid/link/stable url into the DOM
  const [loading, error] = useScript({ src: PLAID_LINK_STABLE_URL })

  // internal state
  const [plaid, setPlaid] = useState(null)
  const [iframeLoaded, setIframeLoaded] = useState(false)
  const [retries, setRetries] = useState(0)

  useEffect(() => {
    // If the link.js script is still loading, return prematurely
    // also, if we pass an empty options config
    if (loading || !options.clientName) {
      return
    }

    if (error) {
      // eslint-disable-next-line no-console
      console.error('Error loading Plaid', error)
      return
    }

    if (!window.Plaid) {
      // eslint-disable-next-line no-console
      console.error('window.Plaid is not set')
      // I don't know why but even after `loading` is false, sometimes in production `window.Plaid` is not set
      // yet, so we retry every 50ms for 5 seconds
      if (retries < 100) {
        // eslint-disable-next-line no-console
        console.error('retrying in a 50ms to see if window.Plaid loads')
        setTimeout(() => {
          setRetries(retries + 1)
        }, 50)
      }
      return
    }

    // eslint-disable-next-line no-console
    console.log('plaid widget loaded successfully')

    // if an old plaid instance exists, destroy it before
    // creating a new one
    if (plaid != null) {
      plaid.exit({ force: true }, () => plaid.destroy())
    }

    const next = createPlaid({
      ...options,
      onLoad: () => {
        setIframeLoaded(true)
        options.onLoad && options.onLoad()
      }
    })

    setPlaid(next)

    // destroy the Plaid iframe factory
    return () => next.exit({ force: true }, () => next.destroy())
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, error, options.token, retries])

  return {
    error,
    ready: !loading || iframeLoaded,
    exit: plaid ? plaid.exit : noop,
    open: plaid ? plaid.open : noop
  }
}
```

and heres the output:

![image](https://user-images.githubusercontent.com/2091439/78076508-cdcde200-7363-11ea-84b9-a47f20669b16.png)

**Comment by RwwL** [comment]
I'm experiencing this error on every fresh, full page load, but it works after hot-module-replacement reloads — definitely worth noting that my project uses Parcel, not webpack.

**Comment by Ruk33** [comment]
I'm experiencing the same issue. After trying for a while, I was able to reproduce it in a very tricky way, here is an example:

```
import React, { useCallback, useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { usePlaidLink } from 'react-plaid-link';

const App = () => {
  const onSuccess = useCallback((token, metadata) => {
    // send token to server
  }, []);

  const config = {
    clientName: 'Your app name',
    env: 'sandbox',
    product: ['auth'],
    publicKey: 'a97b09edb0cafffad47f2eb51fee07',
    onSuccess,
    // ...
  };

  const { open, ready, error } = usePlaidLink(config);

  return (
    <button onClick={() => open()} disabled={!ready}>
      Connect a bank account
    </button>
  );
};

const BuggedComponent = () => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    setVisible(false);
    setInterval(() => setVisible(true), 1)
  }, [])

  return (
    <>
      {visible && <App />}
      {!visible && 'epa'}
    </>
  )
}

ReactDOM.render(<BuggedComponent />, document.getElementById('app'));
```

**Comment by Ruk33** [comment]
I'm experiencing the same issue. After trying for a while, I was able to reproduce it in a very tricky way, here is an example:

```
import React, { useCallback, useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { usePlaidLink } from 'react-plaid-link';

const App = () => {
  const onSuccess = useCallback((token, metadata) => {
    // send token to server
  }, []);

  const config = {
    clientName: 'Your app name',
    env: 'sandbox',
    product: ['auth'],
    publicKey: 'KEY',
    onSuccess,
    // ...
  };

  const { open, ready, error } = usePlaidLink(config);

  return (
    <button onClick={() => open()} disabled={!ready}>
      Connect a bank account
    </button>
  );
};

const BuggedComponent = () => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    setVisible(false);
    setInterval(() => setVisible(true), 1)
  }, [])

  return (
    <>
      {visible && <App />}
      {!visible && 'Hidden'}
    </>
  )
}

ReactDOM.render(<BuggedComponent />, document.getElementById('app'));
```

**Comment by timruffles** [comment]
I've identified one issue that could cause this in the underlying `react-script-hooks` library: https://github.com/hupe1980/react-script-hook/issues/9

I'll see if I can look at a fix today.

**Comment by atomkirk** [comment]
That sounds like exactly whats happening

**Comment by timruffles** [comment]
I'll need to wait for other Plaids to publish a new version here, but I have a branch which pulls in a fixed version of the underlying library: https://github.com/plaid/react-plaid-link/pull/97

**Comment by timruffles** [comment]
This should be fixed in version [2.2.0](https://github.com/plaid/react-plaid-link/releases/tag/v2.2.0).

**Comment by aymanbagabas** [comment]
I'm still getting `Error loading Plaid null` on v2.2.0 every time I refresh a page with PlaidLink. When I use the back button it works fine.

**Comment by timruffles** [comment]
@pbernasconi it appears that although 2.2.0 specifies `react-script-hook@1.0.17` in the JSON, the released `react-plaid-link@2.2.0` module in still contains the old version of `react-script-hook` with the bug identified [here](https://github.com/hupe1980/react-script-hook/issues/9).

```sh
> npm i react-plaid-link@2.2.0
> grep -r document.querySelector node_modules/react-plaid-link/dist/
node_modules/react-plaid-link/dist//index.js:    if (document.querySelector("script[src=\"" + src + "\"]")) {
node_modules/react-plaid-link/dist//index.esm.js:    if (document.querySelector("script[src=\"" + src + "\"]")) {
```

Please could you release `2.2.1` and `2.1.1` after ensuring the fixed version of `react-script-hook` is included in the build?

**Comment by Ruk33** [comment]
Lock hasn't been updated: https://github.com/plaid/react-plaid-link/blob/v2.2.0/yarn.lock#L9143

**Comment by timruffles** [comment]
Just released 2.2.1 - thanks for checking it out @aymanbagabas. I've tested it myself with [this demo app](https://github.com/timruffles/react-plaid-link-86/blob/master/src/App.js#L20) that reproduced the issue and it appears fixed. Would you mind letting me know if 2.2.1 fixes it for you?

**Comment by aymanbagabas** [comment]
Tested it and looks like it's fixed. Thanks for taking the time @timruffles

**Comment by timruffles** [comment]
Awesome, thank you @aymanbagabas 🚀

**Comment by ryanfogarty** [comment]
Found a solid workaround to this issue. Just include <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script> in your index.html file and it eliminates this issue of Plaid being null on load

**Comment by jgonera** [comment]
Circumventing Webpack or any other bundler is not a solution @ryanfogarty. Is the latest version still causing problems for you?

**Comment by donratta** [comment]
Still having issues with this in V3

**Comment by prashantabellad** [comment]
What is the latest update on this??

**Comment by kpavankotesh** [comment]
Facing this issue in 3.0.0. @timruffles can you please check and push a fix?

**Comment by cor1** [comment]
I am seeing this as well, It appears to be somewhat random though.

**Comment by zallarak** [comment]
I see this as well

**Comment by yotavm** [comment]
using version v3.1.0 and still see ```Error loading Plaid null```

**Comment by shubhammetha** [comment]
facing the same issue for V3.2.0

**Comment by SnapeEye** [comment]
v3.2.1 still the same issue. potential fix is merged but not published yet.

**Comment by aleksandrenko** [comment]
I have the same issue with  "react-plaid-link": "3.3.2". I was unable to find an elegant solution so workaround was in order.

1. Extract your button and usePlaidLink in a separate component - let's call it PlaidLinkButton. 
2. Render it in a place like this:

 {
    showFakePlaidButton
        ? <Button isLoading label='Connect' />
        : <PlaidLinkButton onSuccess={() => {}} onError={() => {}} />
}

The goal is to show visually the same button and render the fake for a second or something. 
It's faaaaaar from ideal but it's hidden from the clients.
